import AWSAppSyncClient, {AUTH_TYPE} from 'aws-appsync';
import gql from 'graphql-tag';
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import aws_config from './aws-exports'; //gets resources configs params
import './index.css';
import {ApolloProvider} from 'react-apollo'; // run queries and mutations from UI
import {listPosts} from './graphql/queries';//auto generated by aws-amplify based on graphql endpoint

//instantiate new appsync client by passing aws config params
const client = new AWSAppSyncClient({
	url: aws_config.aws_appsync_graphqlEndpoint,
	region: aws_config.aws_appsync_region,
	auth: {
		type: AUTH_TYPE.API_KEY,
		apiKey: aws_config.aws_appsync_apiKey,
	}
})

client.query({
	query: gql(listPosts)
}).then(({data}) => {
	console.log(data)
})
ReactDOM.render(<App />, document.getElementById('root'));
